### ISSUE TITLE
Reading and processing with promises

### ISSUE THREAD

**Issue by vitaly-t** [spion/promise-streams#7]
In a typical scenario of using streams with promises, one needs to read a stream, and after each read process the data using promises.

For example, reading a large CSV, and for each chunk execute INSERT commands that rely on promises, and once all those have settled, read the next chunk from the stream, and so on.

How can this be achieved using your library?

**Comment by spion** [comment]
```js
var csv = require('csv-stream')
var ps = require('promise-streams')

function pipeFile(csvFile, db) {
  var N = 15
  return fs.createReadStream(csvFile)
  .pipe(csv())
  .pipe(ps.map({concurrent: N}, row => db.insert(...)))
  .wait()
}
```

**Comment by vitaly-t** [comment]
Doesn't quite work for me, the part where `row => db.insert(...)`, let's call it the receiver function.

If the receiver just logs the data into the console, it works.

If the receiver returns a promise that resolves, the code just hangs.

And if the receiver throws an error or returns a rejected promise, the output is:

```
Error: no writecb in Transform class
    at afterTransform (_stream_transform.js:70:33)
    at MapPromiseStream.TransformState.afterTransform (_stream_transform.js:54:12)
    at MapPromiseStream.tryCatcher (D:\NodeJS\tests\node_modules\bluebird\js\main\util.js:26:23)
    at Promise._settlePromiseFromHandler (D:\NodeJS\tests\node_modules\bluebird\js\main\promise.js:507:31)
    at Promise._settlePromiseAt (D:\NodeJS\tests\node_modules\bluebird\js\main\promise.js:581:18)
    at Promise._settlePromises (D:\NodeJS\tests\node_modules\bluebird\js\main\promise.js:697:14)
    at Async._drainQueue (D:\NodeJS\tests\node_modules\bluebird\js\main\async.js:123:16)
    at Async._drainQueues (D:\NodeJS\tests\node_modules\bluebird\js\main\async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (D:\NodeJS\tests\node_modules\bluebird\js\main\async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:368:17)
```

As I noted in my question, my receiver is asynchronous, because every `INSERT` call is asynchronous.

**Comment by vitaly-t** [comment]
Another update...

The only place where I could successfully introduce a promise was after emptying up the read buffer, i.e. I get `readable` event, then call `read` till no more data left, and then I adding a promise works. Interestingly, even if I try to introduce a promise before `read` finished emptying the buffer, the same hang behaviour happens.

So far my only guess: NodeJS affects the way `nextTick` works while `data` is emitted or pending `readable`. This is the only thing to affect the promise functionality. I don't have any better guess right now, because nothing else really makes sense.

**Comment by spion** [comment]
Please post a minimal example that reproduces the issue.

**Comment by vitaly-t** [comment]
Using your own example:

```javascript
var promise = require('bluebird');
var csv = require('csv-parse');
var ps = require('promise-streams');
var fs = require('fs');

function receiver(row) {
    console.log("RECEIVED:", row);
}

function pipeFile(csvFile) {
    var N = 15;
    return fs.createReadStream(csvFile)
        .pipe(csv())
        .pipe(ps.map({concurrent: N}, receiver))
        .wait();
}

pipeFile('D:/NodeJS/PRIMES/large.txt')
    .then(function (data) {
        console.log("DATA:", data);
    }, function (reason) {
        console.log("REASON:", reason);
    });
```
This example works. Now, let's change the receiver as follows:

```javascript
function receiver(row) {
    console.log("RECEIVED:", row);
    return promise.reject('stop');
}
```

It now throws:
```
Error: no writecb in Transform class
    at afterTransform (_stream_transform.js:70:33)
    at MapPromiseStream.TransformState.afterTransform (_stream_transform.js:54:12)
    at MapPromiseStream.tryCatcher (D:\NodeJS\tests\node_modules\bluebird\js\main\util.js:26:23)
    at Promise._settlePromiseFromHandler (D:\NodeJS\tests\node_modules\bluebird\js\main\promise.js:507:31)
    at Promise._settlePromiseAt (D:\NodeJS\tests\node_modules\bluebird\js\main\promise.js:581:18)
    at Promise._settlePromises (D:\NodeJS\tests\node_modules\bluebird\js\main\promise.js:697:14)
    at Async._drainQueue (D:\NodeJS\tests\node_modules\bluebird\js\main\async.js:123:16)
    at Async._drainQueues (D:\NodeJS\tests\node_modules\bluebird\js\main\async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (D:\NodeJS\tests\node_modules\bluebird\js\main\async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:368:17)
```
The same thing happens if we just throw an error there.

However, now that I'm trying to re-create the hanging issue when we return `promise.resolve`, it seems unsuccessful, always works. I don't get it what's happening now...

**Comment by spion** [comment]
Error/rejection issue should be fixed in v2.0

**Comment by vitaly-t** [comment]
>The more I look into it though, the more I become convinced that this shouldn't build on top of node streams - its not just that the implementation is quirky, the whole interface / model are too.

My sentiment exactly, not so much about your library though, rather about the whole compatibility between streams and promises.

You see, I wasn't just experimenting with your library, I as also trying to solve the basic stream read problem on my end, so I wrote [stream.read](https://github.com/vitaly-t/spex/blob/master/docs/code/stream/read.md) method for that. And even though the method does work exactly as described, once you start introducing promise operations during data processing, NodeJS starts behaving unpredictably. Memory consumption along is an issue, but unpredictable data fetching is another issue.

Yesterday after many attempts to fix the issues I kind of gave up, but now I think that injecting pause+resume operations may be the solution.

The problem is, streams were designed to work as fast as possible, while promises are here to mitigate that expectation, and it fails, mostly.

If you get it figured out, that''ll be great! I surely will help you with that!

**Comment by spion** [comment]
@vitaly-t I don't think its a problem with streams in general... just Node's flavor of streams :) I began initial work on the design here https://gist.github.com/spion/ecdc92bc5de5b381da30 and plan to review a few more designs before proceeding:

* [whatwg streams](https://streams.spec.whatwg.org/)
* [mostjs observables](https://github.com/cujojs/most)
* [Dart streams](https://github.com/dart-lang/sdk/blob/master/sdk/lib/async/stream.dart)

Of these, Dart streams look the most promising. For one, they're the only ones meant to work with both binary data and events (objects), like node's streams. Additionally view data decoding as a separate issue and split it off accordingly. Just need to figure out how they deal with multicast and backpressure.

**Comment by vitaly-t** [comment]
Do I understand it right - your are talking about implementing streaming for NodeJS outside the existing NodeJS streams? That implies you would have to write all that as a C++ library. Is that your plan?

Just so, I was developing in C++ for over 15 years, till I called it quits back in 2010, and never touched it since.

And those are all interesting concepts you gave links to, thank you!

In the meantime, I was able to sort out all the problems with readable streams I had within my own implementation. Turns out, I implemented it right, but I was using it wrong, after a long day :)

The moral of this is not to embark on anything grand at the expense of your sack hours :)

**Comment by spion** [comment]
Uhh no, I mean something that doesn't unnecessarily mix up things like node streams does - something with a better API.

**Comment by vitaly-t** [comment]
That's better :) I think the whole event system supported by NodeJS streams is useless within the promise architecture, and to be dumped entirely ;)

**Comment by spion** [comment]
Yeah, I know about the handbook.

So far my impression is that the main problem with node streams are that they also handle buffering, data decoding and multicast (pipe to multiple destinations). If those concerns are extracted out into separate things (buffers and decoders would be transform streams, multicast will be an entirely separate writable stream that can generate multiple readable streams) then it will be possible to make a vastly simpler API without any sacrifice in performance (infact there may be performance gains)

**Comment by vitaly-t** [comment]
Just stumbled upon: [highland](https://github.com/caolan/highland)

**Comment by spion** [comment]
Highland is okay, but its API doesn't play nicely with promises and as such doesn't compose very well. Dart is still in the lead :)

**Comment by vitaly-t** [comment]
I find it hard to trust a library that got 10 times more open issues than the number of stars: [dart](https://github.com/dart-lang/sdk)

386 stars and 3,368 open issues does not impress :)

**Comment by spion** [comment]
Dart is not a library, its an entirely different language and virtual machine. The star to issue ratio doesn't mean all that much (in this particular case it seems to be google engineers publicly working on the whole thing rather than using a private tracker on the side)

**Comment by vitaly-t** [comment]
If you decide to start on this, I would strongly suggest to use Promises/A+ standard, and not any particular promise library.

I have done 2 libraries so far built on the Promises/A+ standard: [pg-promise](https://github.com/vitaly-t/pg-promise) and [spex](https://github.com/vitaly-t/spex).

Each of them is using only the three basic promise facility:

* construct a new promise with a callback function
* resolve a promise with some result data
* reject a promise with a reason

Nothing else is needed to implement a proper promise-based stream.

The code I'm using to wrap up a nice accessor to any promise library:

```javascript
//////////////////////////////////////////
// Parses and validates a promise library;
function parsePromiseLib(lib) {
    if (lib) {
        var t = typeof lib;
        if (t === 'function' || t === 'object') {
            var root = lib.Promise instanceof Function ? lib.Promise : lib,
                methods = ['resolve', 'reject'], // key promise methods;
                success = true;
            var promise = function (func) {
                return new root(func);
            };
            methods.forEach(function (m) {
                promise[m] = root[m];
                success = success && root[m] instanceof Function;
            });
            if (success) {
                return promise;
            }
        }
    }
    throw new TypeError("Invalid promise library specified.");
}
```
Then you use it like this:
```javascript
var $p = parsePromiseLib(Promise);
```

**Comment by vitaly-t** [comment]
@spion how are you getting on with this? ;) I thought I'd check back, since you didn't reply. I started to think maybe you didn't like my last suggestion, since you seem to be an avid supporter of Bluebird all the way... :)

**Comment by spion** [comment]
@vitaly-t its performance I'm worried about, and bluebird offers `Promise.bind` which avoids the need to use closures. And this is meant to be a bluebird companion module. So yeah, I don't think I'm going with a generic solution.

Working on some other stuff at the moment, not really ready to tackle this one yet.

**Comment by vitaly-t** [comment]
@spion , ok, take your time ;)

As for the Bluebird, not only it is used by 1/3 of the market at best, but I don't think all those promises will have a future within NodeJS.

You see, the current version of ES6 Promise is already so well performing, and it only gets faster with every release. The only thing it lacks is all the extra extensions. The future for promise libraries is in extending the standard ES6, not in replacing it.

**Comment by spion** [comment]
My prediction is that it will take a long, long time before native promises are anywhere near Bluebird (right now they're 5-9 times slower). And like with most JS builtins, their API is so bare-bones that its almost useless.

Market share isn't all that important - having a nice solid base of libraries that can handle most problems in a performant and reliable way is. 

For a while now I've been thinking how awesome it would be if there was an alternate node base library, "blue core" (if @petkaantonov is okay with that name lol), which would offer an alternative to the core libraries and concepts offered by node. Bluebird aleady does this for all callback-based APIs, but it doesn't do anything about streams and event-emitters. For this to be successful, it should be relatively easy to convert any stream/EE library to the new API - as easy as promisification is in bluebird.

**Comment by vitaly-t** [comment]
I don't know where I you got the figures of 5-10 times slower, or from what times it came, but in the current NodeJS version 4.2.1, ES6 Promise often outperforms Bluebird, and has even smaller memory print. I know because I've run a few of my own Benchmarks against it.

**Comment by spion** [comment]
bluebird's benchmark

parallel:

```
results for 10000 parallel executions, 1 ms per I/O op

file                                time(ms)  memory(MB)
callbacks-baseline.js                    154       37.89
promises-bluebird.js                     379       86.16
promises-bluebird-generator.js           428       90.11
promises-cujojs-when.js                  589      141.11
promises-tildeio-rsvp.js                 596      189.70
callbacks-caolan-async-parallel.js      1061      190.99
promises-lvivski-davy.js                1221      248.66
promises-calvinmetcalf-lie.js           1404      352.85
promises-ecmascript6-native.js          1925      508.98
promises-dfilatov-vow.js                2009      500.31
promises-then-promise.js                2269      660.95
promises-medikoo-deferred.js            4720      535.76
promises-obvious-kew.js                 6771     1021.60

Platform info:
Darwin 14.3.0 x64
Node.JS 4.2.0
V8 4.5.103.35
Intel(R) Core(TM) i7-4850HQ CPU @ 2.30GHz × 8
```

doxbee-sequential:

```
results for 10000 parallel executions, 1 ms per I/O op

file                                     time(ms)  memory(MB)
callbacks-baseline.js                         158       32.42
promises-bluebird-generator.js                206       33.81
promises-bluebird.js                          269       44.73
promises-cujojs-when.js                       369       76.06
promises-tildeio-rsvp.js                      377       71.75
callbacks-caolan-async-waterfall.js           461       77.54
promises-lvivski-davy.js                      547      111.25
promises-dfilatov-vow.js                      659      141.61
promises-calvinmetcalf-lie.js                 692      150.41
promises-ecmascript6-native.js                826      183.27
generators-tj-co.js                           846      137.43
promises-obvious-kew.js                      1355      266.61
promises-then-promise.js                     1488      193.39
promises-medikoo-deferred.js                 2283      219.16
observables-Reactive-Extensions-RxJS.js      2765      283.17
observables-pozadi-kefir.js                  3049      163.79
promises-kriskowal-q.js                     12319      829.68
observables-baconjs-bacon.js.js             18990      858.17
observables-caolan-highland.js              28695      530.23

Platform info:
Darwin 14.3.0 x64
Node.JS 4.2.0
V8 4.5.103.35
Intel(R) Core(TM) i7-4850HQ CPU @ 2.30GHz × 8
```
